version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    command: "/start-reload.sh"
    environment:
      VERSION: "latest"
      APP_MODULE: "app.main:app"
      LOG_LEVEL: "debug"
      ACCESS_LOG: "/dev/null"
      APP_NAME: "ML Document Classifier FastAPI Demo"
      # ------------ document classifier -------------------
      MODEL_NAME: davidhajdu/fine-tuned-rvl-cdip
      TOKENIZER_NAME: davidhajdu/fine-tuned-rvl-cdip

    volumes:
      - ./app:/code/app
